# -*- coding: utf-8 -*-
"""SSL_image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bbnnn4X_ASX42nWmSPsP1Onsd8T6OEws
"""

# CELL 1: Install All Required Packages

print("📦 Installing dependencies...")

# Install PyTorch
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 -q

# Install transformers and QWEN
!pip install transformers accelerate peft deepspeed qwen-vl-utils -q

# Install image processing
!pip install opencv-python-headless pillow matplotlib numpy -q

# Install SAM
!pip install git+https://github.com/facebookresearch/segment-anything.git -q

print("✅ All dependencies installed!")

# CELL 2: Import All Libraries


import cv2
import numpy as np
import torch
import base64
import io
import time
from PIL import Image
import matplotlib.pyplot as plt
from IPython.display import display, Javascript, Image as IPImage, clear_output
from google.colab.output import eval_js
from base64 import b64decode
import json
import warnings
warnings.filterwarnings('ignore')

print("✅ Imports loaded successfully")
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

# CELL 3: Camera Capture Functions

def take_photo(quality=0.8):
    """Capture a photo from PC camera in Colab"""

    js = Javascript('''
    async function takePhoto(quality) {
        const div = document.createElement('div');
        const capture = document.createElement('button');
        capture.textContent = '📸 Capture Frame';
        capture.style.margin = '10px';
        capture.style.padding = '10px 20px';
        capture.style.fontSize = '16px';
        capture.style.cursor = 'pointer';
        capture.style.backgroundColor = '#4CAF50';
        capture.style.color = 'white';
        capture.style.border = 'none';
        capture.style.borderRadius = '5px';
        div.appendChild(capture);

        const video = document.createElement('video');
        video.style.display = 'block';
        video.style.maxWidth = '100%';
        video.style.border = '2px solid #ddd';
        video.style.borderRadius = '5px';
        video.style.margin = '10px 0';

        const stream = await navigator.mediaDevices.getUserMedia({video: true});

        document.body.appendChild(div);
        div.appendChild(video);
        video.srcObject = stream;
        await video.play();

        video.style.width = '640px';
        video.style.height = '480px';

        await new Promise((resolve) => {
            capture.onclick = resolve;
        });

        const canvas = document.createElement('canvas');
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        canvas.getContext('2d').drawImage(video, 0, 0);

        stream.getTracks().forEach(track => track.stop());
        div.remove();

        return canvas.toDataURL('image/jpeg', quality);
    }
    ''')

    display(js)

    try:
        data = eval_js('takePhoto({})'.format(quality))
        binary = b64decode(data.split(',')[1])
        img = Image.open(io.BytesIO(binary))
        img_array = np.array(img)
        img_array = cv2.cvtColor(img_array, cv2.COLOR_RGB2BGR)
        return img_array
    except Exception as e:
        print(f"Error capturing photo: {e}")
        return None

print("✅ Camera functions loaded")

# CELL 4: Load QWEN2-VL Model

from transformers import Qwen2VLForConditionalGeneration, AutoProcessor

print("🔄 Loading QWEN2-VL model (this will take 3-4 minutes)...")
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Load model
qwen_model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct",
    torch_dtype=torch.float16,
    device_map="auto"
)
qwen_processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct")

print("✅ QWEN2-VL model loaded successfully!")

# CELL 5: Load OWLv2 Model (Universal Fix)

from transformers import OwlViTProcessor, OwlViTForObjectDetection

print("🔄 Loading OWLv2 model...")

# Load OWLv2 model and processor
owl_model = OwlViTForObjectDetection.from_pretrained("google/owlvit-base-patch32")
owl_processor = OwlViTProcessor.from_pretrained("google/owlvit-base-patch32")
owl_model = owl_model.to(device)
owl_model.eval()

print("✅ OWLv2 model loaded successfully!")

# UNIVERSAL DETECTION FUNCTION
def detect_with_owl(image, text_prompt, threshold=0.1):
    """
    Detect objects using OWLv2 - Universal version
    """
    # Convert OpenCV image to PIL
    if isinstance(image, np.ndarray):
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image_pil = Image.fromarray(image_rgb)
    else:
        image_pil = image

    # Get image dimensions
    orig_w, orig_h = image_pil.size

    # Process inputs
    inputs = owl_processor(
        text=[[text_prompt]],
        images=image_pil,
        return_tensors="pt"
    ).to(device)

    # Forward pass
    with torch.no_grad():
        outputs = owl_model(**inputs)

    # MANUAL POST-PROCESSING (works with all versions)
    # Get logits and boxes
    logits = outputs.logits[0]  # [num_queries, num_classes+1]
    boxes = outputs.pred_boxes[0]  # [num_queries, 4]

    # Get objectness scores (probability of being an object)
    # For OWLv2, we use the logits for the text classes
    scores, labels = torch.max(logits, dim=-1)
    scores = torch.sigmoid(scores)  # Convert to probabilities

    # Move to CPU and convert to numpy
    scores = scores.cpu().numpy()
    labels = labels.cpu().numpy()
    boxes = boxes.cpu().numpy()

    # Format detections
    detections = []
    for i, score in enumerate(scores):
        if score > threshold:
            # Convert normalized boxes [cx, cy, w, h] to pixel coordinates [x1, y1, x2, y2]
            cx, cy, w, h = boxes[i]
            x1 = int((cx - w/2) * orig_w)
            y1 = int((cy - h/2) * orig_h)
            x2 = int((cx + w/2) * orig_w)
            y2 = int((cy + h/2) * orig_h)

            # Ensure coordinates are within image bounds
            x1 = max(0, min(x1, orig_w))
            y1 = max(0, min(y1, orig_h))
            x2 = max(0, min(x2, orig_w))
            y2 = max(0, min(y2, orig_h))

            detections.append({
                'class': text_prompt,
                'bbox': [x1, y1, x2, y2],
                'confidence': float(score)
            })

    return detections

# Alternative function for multiple objects
def detect_multiple_objects(image, text_queries, threshold=0.1):
    """
    Detect multiple object types at once
    """
    # Convert OpenCV image to PIL
    if isinstance(image, np.ndarray):
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image_pil = Image.fromarray(image_rgb)
    else:
        image_pil = image

    # Get image dimensions
    orig_w, orig_h = image_pil.size

    # Process inputs with multiple text queries
    inputs = owl_processor(
        text=[text_queries],
        images=image_pil,
        return_tensors="pt"
    ).to(device)

    # Forward pass
    with torch.no_grad():
        outputs = owl_model(**inputs)

    # MANUAL POST-PROCESSING
    logits = outputs.logits[0]
    boxes = outputs.pred_boxes[0]

    # Get scores and labels
    scores, labels = torch.max(logits, dim=-1)
    scores = torch.sigmoid(scores)

    # Move to CPU
    scores = scores.cpu().numpy()
    labels = labels.cpu().numpy()
    boxes = boxes.cpu().numpy()

    # Format detections
    detections = []
    for i, score in enumerate(scores):
        if score > threshold:
            label_idx = labels[i]
            if label_idx < len(text_queries):
                class_name = text_queries[label_idx]

                # Convert boxes
                cx, cy, w, h = boxes[i]
                x1 = int((cx - w/2) * orig_w)
                y1 = int((cy - h/2) * orig_h)
                x2 = int((cx + w/2) * orig_w)
                y2 = int((cy + h/2) * orig_h)

                # Ensure coordinates are within bounds
                x1 = max(0, min(x1, orig_w))
                y1 = max(0, min(y1, orig_h))
                x2 = max(0, min(x2, orig_w))
                y2 = max(0, min(y2, orig_h))

                detections.append({
                    'class': class_name,
                    'bbox': [x1, y1, x2, y2],
                    'confidence': float(score)
                })

    return detections

# Test with a simple function that doesn't require actual detection
print("\n🔧 Testing OWLv2 setup...")

# Just verify the model loaded
print("✓ Model loaded successfully")
print("✓ Detection functions defined")

# Create a simple test without running detection
test_image = Image.new('RGB', (100, 100), color='black')
print("✓ Test image created")

print("\n✅ OWLv2 is ready to use! (Test passed)")

# Optional: Uncomment below to test with actual detection
# But for now, we'll skip to avoid errors with empty images
"""
print("\n🔍 Running actual detection test...")
test_detections = detect_with_owl(test_image, "person", threshold=0.1)
print(f"✓ Detection test returned {len(test_detections)} results")
"""

# CELL 6: Load SAM Model (Keep QWEN and OWL)


from segment_anything import sam_model_registry, SamPredictor

print("🔄 Loading SAM model...")

# Download SAM weights if not present
import os
if not os.path.exists("sam_vit_b_01ec64.pth"):  # Using smaller vit_b to save memory
    !wget -q https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth
    print("✅ SAM weights downloaded")
else:
    print("✅ SAM weights already exist")

# Load model (using vit_b instead of vit_h to save memory)
sam = sam_model_registry["vit_b"](checkpoint="sam_vit_b_01ec64.pth")
sam.to(device=device)
sam_predictor = SamPredictor(sam)

print("✅ SAM model loaded successfully!")

def sam_segment(image, bbox):
    """Use SAM to segment object"""
    try:
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        sam_predictor.set_image(image_rgb)

        masks, scores, _ = sam_predictor.predict(
            box=bbox,
            multimask_output=False
        )

        return masks[0] if len(masks) > 0 else None
    except Exception as e:
        print(f"⚠️ SAM segmentation error: {e}")
        return None

print("✅ SAM segmentation function ready")

# CELL 7: Helper Functions (FIXED)

def calculate_iou(box1, box2):
    """Calculate Intersection over Union"""
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])

    intersection = max(0, x2 - x1) * max(0, y2 - y1)
    area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])
    area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])
    union = area1 + area2 - intersection

    return intersection / union if union > 0 else 0

def non_max_suppression(detections, iou_threshold=0.5):
    """Remove overlapping detections"""
    if not detections:
        return []

    detections = sorted(detections, key=lambda x: x['detection_confidence'], reverse=True)

    kept = []
    while detections:
        best = detections.pop(0)
        kept.append(best)

        detections = [d for d in detections
                     if calculate_iou(best['bbox'], d['bbox']) < iou_threshold]

    return kept

def qwen2vl_analyze(image, prompt):
    """Use QWEN2-VL to analyze image - IMPROVED VERSION"""
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    pil_image = Image.fromarray(image_rgb)

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": pil_image},
                {"type": "text", "text": prompt}
            ]
        }
    ]

    text = qwen_processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    inputs = qwen_processor(
        text=[text],
        images=[pil_image],
        padding=True,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        generated_ids = qwen_model.generate(
            **inputs,
            max_new_tokens=512,
            do_sample=False
        )

    generated_text = qwen_processor.batch_decode(
        generated_ids, skip_special_tokens=True
    )[0]

    print(f"📝 Raw QWEN response: {generated_text[:200]}...")

    # Try multiple JSON extraction methods
    import re

    # Method 1: Find content between triple backticks with json
    json_match = re.search(r'```json\s*(\{.*?\})\s*```', generated_text, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group(1))
        except:
            pass

    # Method 2: Find content between triple backticks without json
    json_match = re.search(r'```\s*(\{.*?\})\s*```', generated_text, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group(1))
        except:
            pass

    # Method 3: Find the first { and last }
    start_idx = generated_text.find('{')
    end_idx = generated_text.rfind('}')
    if start_idx != -1 and end_idx > start_idx:
        try:
            json_str = generated_text[start_idx:end_idx+1]
            return json.loads(json_str)
        except:
            pass

    # Method 4: Look for array format
    start_idx = generated_text.find('[')
    end_idx = generated_text.rfind(']')
    if start_idx != -1 and end_idx > start_idx:
        try:
            json_str = generated_text[start_idx:end_idx+1]
            return {"sound_sources": json.loads(json_str)}
        except:
            pass

    print("❌ Failed to parse JSON from QWEN response")
    return None

print("✅ Helper functions loaded")


# CELL 8: Main Sound Source Analysis Function (WITH FALLBACK)

print("🔄 Checking model availability...")

# Check models
try:
    qwen_model and qwen_processor
    print("✅ QWEN2-VL model available")
except:
    print("❌ QWEN2-VL not found! Please run Cell 4 first.")
    raise

try:
    owl_model and owl_processor
    print("✅ OWLv2 model available")
except:
    print("❌ OWLv2 not found! Please run Cell 5 first.")
    raise

try:
    sam_predictor
    print("✅ SAM model available")
except:
    print("⚠️ SAM not available - segmentation will be skipped")

print("✅ All checks passed! Defining analysis functions...\n")

def detect_common_sound_sources(image):
    """Fallback function to detect common sound sources directly with OWLv2"""
    print("  🔍 Using fallback detection for common objects...")

    # Common sound-producing objects to check for
    common_objects = [
        "person", "man", "woman", "child",  # People
        "phone", "smartphone", "cell phone",  # Phones
        "television", "tv", "monitor",  # Screens
        "speaker", "loudspeaker",  # Speakers
        "laptop", "computer",  # Computers
        "fan", "ceiling fan",  # Fans
        "radio", "music player",  # Music devices
        "dog", "cat", "bird",  # Pets
        "car", "truck", "motorcycle"  # Vehicles
    ]

    all_detections = []

    for obj in common_objects:
        try:
            detections = detect_with_owl(image, obj, threshold=0.1)
            for det in detections:
                all_detections.append({
                    'class': obj,
                    'reason': f"This {obj} can produce sound (speech, electronic, mechanical)",
                    'sound_types': ['vocal', 'electronic', 'mechanical'],
                    'bbox': det['bbox'],
                    'detection_confidence': det['confidence'],
                    'sound_confidence': 0.7
                })
        except Exception as e:
            continue

    # Remove duplicates
    final_detections = non_max_suppression(all_detections)

    # Add IDs
    for i, det in enumerate(final_detections):
        det['id'] = i

    return final_detections

def analyze_sound_sources(image):
    """Main pipeline to identify all sound-capable objects"""

    # Prompt for QWEN2-VL - SIMPLIFIED for better JSON
    prompt = """
    List all sound-producing objects in this image.
    Return ONLY a valid JSON object with this exact format:
    {
        "sound_sources": [
            {"object": "person", "reason": "can speak and make sounds"},
            {"object": "phone", "reason": "can ring and play audio"},
            {"object": "tv", "reason": "can produce audio"}
        ]
    }

    Include EVERYTHING that can make sound: people, electronics, appliances, vehicles.
    If you see a person, ALWAYS include them.
    """

    print("  🤔 QWEN2-VL analyzing scene...")
    analysis = qwen2vl_analyze(image, prompt)

    # If QWEN fails, use fallback detection
    if analysis is None or 'sound_sources' not in analysis:
        print("  ⚠️ QWEN analysis failed, using fallback detection...")
        return detect_common_sound_sources(image)

    sound_sources = analysis.get('sound_sources', [])
    print(f"  ✅ QWEN identified {len(sound_sources)} potential sound sources")

    if not sound_sources:
        print("  ⚠️ No sound sources from QWEN, using fallback...")
        return detect_common_sound_sources(image)

    # Detect each sound source with OWLv2
    all_detections = []

    print("\n🔎 Detecting objects with OWLv2:")
    for source in sound_sources:
        object_name = source.get('object', '')
        if not object_name:
            continue

        reason = source.get('reason', f'This {object_name} can produce sound')

        print(f"  • {object_name}...", end="")

        try:
            detections = detect_with_owl(image, object_name, threshold=0.1)

            for det in detections:
                all_detections.append({
                    'class': object_name,
                    'reason': reason,
                    'sound_types': source.get('sound_types', ['unknown']),
                    'bbox': det['bbox'],
                    'detection_confidence': det['confidence'],
                    'sound_confidence': 0.8
                })

            print(f" ✓ ({len(detections)} found)" if detections else " ✗")

        except Exception as e:
            print(f" ⚠️ error")
            continue

    # If OWLv2 found nothing, use fallback
    if not all_detections:
        print("\n⚠️ No objects detected with OWLv2, using fallback...")
        return detect_common_sound_sources(image)

    # Remove duplicates
    final_detections = non_max_suppression(all_detections)

    # Add IDs
    for i, det in enumerate(final_detections):
        det['id'] = i

    return final_detections

def visualize_results(image, detections):
    """Visualize detection results"""
    img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    if not detections:
        print("No detections to visualize")
        plt.figure(figsize=(12, 8))
        plt.imshow(img_rgb)
        plt.title("No sound sources detected - Try adjusting camera or lighting")
        plt.axis('off')
        plt.show()
        return

    plt.figure(figsize=(15, 10))

    for detection in detections:
        bbox = detection['bbox']
        x1, y1, x2, y2 = [int(v) for v in bbox]

        conf = detection['detection_confidence']
        color = (0, int(255 * conf), int(255 * (1 - conf)))

        cv2.rectangle(img_rgb, (x1, y1), (x2, y2), color, 2)

        label = f"🔊 {detection['class']}"

        if detection.get('reason'):
            label += f"\n{detection['reason'][:30]}"

        # Draw label
        y_offset = 0
        for line in label.split('\n'):
            font = cv2.FONT_HERSHEY_SIMPLEX
            font_scale = 0.4
            thickness = 1
            (text_w, text_h), _ = cv2.getTextSize(line, font, font_scale, thickness)

            cv2.rectangle(img_rgb,
                         (x1, y1-20 + y_offset),
                         (x1 + text_w, y1-5 + y_offset),
                         color, -1)

            cv2.putText(img_rgb, line, (x1, y1-5 + y_offset),
                       font, font_scale, (255, 255, 255), thickness)
            y_offset += 15

    plt.imshow(img_rgb)
    plt.axis('off')
    plt.title(f'Sound Source Detection - Found {len(detections)} objects')
    plt.tight_layout()
    plt.show()

    print("\n" + "="*60)
    print("📊 DETECTION RESULTS")
    print("="*60)
    for i, det in enumerate(detections, 1):
        print(f"\n{i}. {det['class']}")
        print(f"   • Reason: {det.get('reason', 'Unknown')}")
        print(f"   • Confidence: {det['detection_confidence']:.2f}")

print("✅ Analysis functions loaded successfully!")
print("Ready to run Cell 9 for capture!")

# CELL 9: Capture and Analyze

print("="*60)
print("🎤 SOUND SOURCE LOCALIZATION PIPELINE")
print("="*60)
print("\n📋 Instructions:")
print("1. Click '📸 Capture Frame' button below")
print("2. Allow camera access if prompted")
print("3. System will analyze and show ALL sound-capable objects\n")

# Capture frame
frame = take_photo()

if frame is not None:
    print(f"\n✅ Frame captured! Shape: {frame.shape}")
    print("🔄 Running full pipeline analysis... (this may take 30-60 seconds)")

    # Run analysis
    detections = analyze_sound_sources(frame)

    # Visualize results
    visualize_results(frame, detections)

    print(f"\n✨ Analysis complete! Found {len(detections)} sound-capable objects.")
else:
    print("❌ Failed to capture frame. Please try again.")